services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: deliverar_db
      POSTGRES_USER: deliverar_user
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: agus@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
        - "5050:80"

volumes:
  db_data:
